# Generated by Django 4.2 on 2023-05-10 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wat_url', models.URLField(verbose_name='Whatsapp ссылка')),
                ('wat_txt', models.TextField(verbose_name='Имя контакта')),
                ('tg_url', models.URLField(verbose_name='Telegram ссылка')),
                ('tg_txt', models.TextField(verbose_name='Имя контакта')),
                ('about_txt', models.TextField(verbose_name='Информационный текст')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Описание')),
                ('date_post', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания поста')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь создавший пост')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
