# Generated by Django 4.2.1 on 2023-05-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Администратор'), (2, 'Продавец'), (3, 'Курьер'), (4, 'Сборщик'), (5, 'Покупатель')], default=5, verbose_name='Роль'),
        ),
    ]
