# Generated by Django 4.2 on 2023-05-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wat_url', models.URLField(verbose_name='Whatsapp ссылка')),
                ('tg_url', models.URLField(verbose_name='Telegram ссылка')),
                ('about_txt', models.TextField(verbose_name='Информационный текст')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
    ]
